### PR TITLE
More work on UBI image to get PHP+Apache functioning

### PR DESCRIPTION
**Pull request by bostrt**
Very much a WIP right now. This PR will contain some work to get this UBI based image fully functioning.

### CODE REVIEW

**Comment by bostrt** [comment]
Working on this pending discussion about supporting OpenEMR 5.0.2 or 5.0.3 (dev) initially

**Comment by bostrt** [comment]
Latest changes seem promising, the following test command will connect to database and initialize:
```
$ podman run -e SWARM_MODE=no -e MYSQL_HOST=<host> -e MYSQL_ROOT_PASS=<pass> -p 8443:8443 --rm -it -v $(pwd):/etc/ssl/certs/  quay.io/bostrt/openemr-test:latest
```

**Comment by bostrt** [comment]
@isimluk I'd like your review if you have time.

**Review by isimluk — APPROVED** [review]

**Comment by isimluk** [comment]
LGTM! Well done!

**Pull request merged**
